### ISSUE TITLE
[BUG] App crashes when open books with no episode

### ISSUE THREAD

**Issue by kevin5871** [nutyworks/SyosetuViewer#12]
**Describe the bug**
App crashes when open "n3522gq"
> http://ncode.syosetu.com/n3522gq

**To Reproduce**
1. Add "n3522gq"
2. Try to open it
3. Shutdown.

**Expected behavior**
Some Error Message?

**Smartphone (please complete the following information):**
 - S10 / Android Q / 2.0.0-alpha1

**Additional context**

**Comment by nutyworks** [comment]
Already fixed with commit 87b6489f987dc3ba418c476f6dbeaccda72b7f3a. 
However, there is an issue that the content is not displayed properly with short stories.
